name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          cd cf-dashboard
          npm ci
          npm run build
          mkdir -p ../docs
          cp -r build/* ../docs/

      - name: Commit and push changes
        run: |
          cd docs
          git config --global user.name 'GitHub Actions'
          git config --global user.email "noreply"
          git add docs/
          git commit -m "Deploy to GitHub Pages"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
