name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies and build
        run: |
          cd cf-dashboard
          yarn install
          yarn build
          cp -r build/* ../docs/

      - name: Deploy to GitHub Pages
        run: |
          cd docs
          git config --global user.name 'GitHub Actions'
          git config --global user.email "noreply"
          git add docs/
          git commit -m "Deploy to GitHub Pages"
          git push origin main
